flowchart TD
  subgraph Minikube
    Ingress --> FrontendPod
    Ingress --> ProductPod
    Ingress --> OrderPod
    ProductPod --> PostgresSvc
    OrderPod --> PostgresSvc
    ProductPod --> OTelCollector
    OrderPod --> OTelCollector
  end
  OTelCollector --> HostCollector
  HostCollector --> ClickHouse
