from __future__ import annotations

import json
from pathlib import Path


class DocumentationBuilder:
    def __init__(self, docs: Path) -> None:
        self.docs = docs

    def build(self, model: dict, evidence, results: list[dict], diagrams: list[str], screenshots: list[str]) -> list[str]:
        testcases_source = Path(model['testcases_path'])
        testcases_target = self.docs / 'test-cases.md'
        if testcases_source.exists():
            testcases_target.write_text(testcases_source.read_text(encoding='utf-8'), encoding='utf-8')
        records = evidence.records
        pages = {
            'index.md': self._index(results),
            'system-architecture.md': self._architecture(model, diagrams),
            'validation-summary.md': self._summary(results, records, screenshots),
            'validation-results.md': '# Validation Results\n\n```json\n' + json.dumps(results, indent=2) + '\n```\n',
            'secret-management.md': self._secret_management(records),
            'screenshots.md': self._screenshots(screenshots),
            'system-evidence.md': self._system_evidence(records),
            'observability-architecture.md': self._observability(records),
            'gitops-deployment.md': self._gitops(records),
            'vault-secret-management.md': self._vault(records),
            'application-workflow.md': self._application(records),
        }
        for name, content in pages.items():
            (self.docs / name).write_text(content, encoding='utf-8')
        return sorted(set(pages) | {'test-cases.md'})

    def _index(self, results: list[dict]) -> str:
        passed = sum(1 for item in results if item['success'])
        failed = len(results) - passed
        return f"# LeninKart Validation\n\nThis site is generated by the automated validation engine.\n\n- Passed modules: {passed}\n- Failed modules: {failed}\n- Canonical test catalog: [test-cases.md](test-cases.md)\n- Execution summary: [validation-summary.md](validation-summary.md)\n- Observability evidence: [observability-architecture.md](observability-architecture.md)\n- GitOps evidence: [gitops-deployment.md](gitops-deployment.md)\n- Vault evidence: [vault-secret-management.md](vault-secret-management.md)\n- System evidence: [system-evidence.md](system-evidence.md)\n"

    def _architecture(self, model: dict, diagrams: list[str]) -> str:
        links = '\n'.join(f'- [docs/diagrams/{name}](diagrams/{name})' for name in diagrams)
        services = '\n'.join(f'- `{service}`' for service in model['services'])
        repos = '\n'.join(f'- `{name}`: `{path}`' for name, path in model['repositories'].items())
        return f"# System Architecture\n\n## Core Services\n\n{services}\n\n## Repositories\n\n{repos}\n\n## Diagrams\n\n{links}\n"

    def _summary(self, results: list[dict], records: dict, screenshots: list[str]) -> str:
        lines = ['# Validation Summary', '']
        for result in results:
            status = 'PASS' if result['success'] else 'FAIL'
            lines.append(f"- `{result['name']}`: {status} - {result['summary']}")
        lines += ['', '## Evidence Summary', '']
        lines.append(f"- Screenshot count: {len(screenshots)}")
        obs = records.get('results', {}).get('observability', {})
        vault = records.get('results', {}).get('vault', {})
        kafka = records.get('results', {}).get('kafka', {})
        lines.append(f"- Kafka topics verified: {', '.join(kafka.get('topics', []))}")
        lines.append(f"- Vault secret keys verified: {', '.join(vault.get('secret_value_keys', []))}")
        lines.append(f"- Observability sections explored: {len(obs.get('sections', []))}")
        lines += ['', '## Screenshot References', '']
        for file_name in sorted(screenshots):
            lines.append(f'- [screenshots/{file_name}](screenshots/{file_name})')
        lines.append('')
        lines.append('See [validation-results.md](validation-results.md) for the full payload.')
        return '\n'.join(lines)

    def _secret_management(self, records: dict) -> str:
        vault = records.get('results', {}).get('vault', {})
        keys = ', '.join(vault.get('secret_value_keys', [])) or 'n/a'
        return f'# Secret Management\n\nVault is validated as the source of truth, `ClusterSecretStore/vault-backend` is checked for readiness, ExternalSecret sync state is captured during execution, and representative secret values are validated during the run.\n\n- Verified secret keys: {keys}\n- Detailed evidence: [vault-secret-management.md](vault-secret-management.md)\n'

    def _screenshots(self, screenshots: list[str]) -> str:
        lines = ['# Screenshots', '']
        for file_name in sorted(screenshots):
            lines.append(f'![{file_name}](screenshots/{file_name})')
            lines.append('')
        return '\n'.join(lines)

    def _system_evidence(self, records: dict) -> str:
        return '# System Evidence\n\n```json\n' + json.dumps(records, indent=2) + '\n```\n'

    def _section_list(self, sections: list[dict]) -> str:
        lines: list[str] = []
        for section in sections:
            lines.append(f"### {section.get('title', 'Section')}")
            lines.append(section.get('explanation', ''))
            screenshot = section.get('screenshot')
            if screenshot:
                lines.append(f"\n![{screenshot}](screenshots/{screenshot})")
            if 'path' in section:
                lines.append(f"\n- Route: `{section['path']}`")
            if 'data_present' in section:
                lines.append(f"- Data present: `{section['data_present']}`")
            matched = section.get('matched_terms')
            if matched:
                lines.append(f"- Matched telemetry markers: {', '.join(matched)}")
            lines.append('')
        return '\n'.join(lines)

    def _observability(self, records: dict) -> str:
        obs = records.get('results', {}).get('observability', {})
        sections = obs.get('sections', [])
        lines = ['# Observability Architecture', '', 'This report explains the observability surfaces explored by the validator and what each page represents operationally.', '']
        lines.append(f"- Observer health endpoint OK: `{obs.get('observer_health')}`")
        lines.append(f"- Kafka telemetry detected: `{obs.get('kafka_metrics')}`")
        lines.append(f"- Required service detection OK: `{obs.get('required_service_detection_ok')}`")
        lines.append('')
        lines.append('## Explored Pages')
        lines.append('')
        lines.append(self._section_list(sections))
        return '\n'.join(lines)

    def _gitops(self, records: dict) -> str:
        gitops = records.get('results', {}).get('gitops', {})
        sections = gitops.get('sections', [])
        lines = ['# GitOps Deployment', '', 'This report captures the ArgoCD UI evidence used to validate GitOps application inventory, sync state, and revision history.', '']
        failing = gitops.get('failing', [])
        lines.append(f"- Failing core apps observed: `{len(failing)}`")
        lines.append('')
        lines.append('## Explored Pages')
        lines.append('')
        lines.append(self._section_list(sections))
        return '\n'.join(lines)

    def _vault(self, records: dict) -> str:
        vault = records.get('results', {}).get('vault', {})
        sections = vault.get('sections', [])
        lines = ['# Vault Secret Management', '', 'This report captures the Vault UI evidence and KV verification performed by the validator.', '']
        lines.append(f"- Vault ready: `{vault.get('vault_ready')}`")
        lines.append(f"- Vault sealed: `{vault.get('sealed')}`")
        lines.append(f"- ClusterSecretStore ready: `{vault.get('store_ready')}`")
        lines.append(f"- KV paths: {', '.join(vault.get('kv_paths', []))}")
        lines.append('')
        lines.append('## Explored Pages')
        lines.append('')
        lines.append(self._section_list(sections))
        return '\n'.join(lines)

    def _application(self, records: dict) -> str:
        frontend = records.get('results', {}).get('frontend', {})
        traffic = records.get('traffic', {})
        lines = ['# Application Workflow', '', 'This page summarizes the validated LeninKart user workflow that was used to generate business traffic and observability evidence.', '']
        lines.append(f"- Validation user: `{frontend.get('user_email') or traffic.get('user_email', '')}`")
        lines.append(f"- Product created: `{frontend.get('product_name') or traffic.get('product_name', '')}`")
        lines.append(f"- Orders requested: `{frontend.get('orders_requested') or traffic.get('orders_requested')}`")
        lines.append(f"- Product visible in UI: `{frontend.get('product_visible')}`")
        lines.append(f"- Order ledger visible: `{frontend.get('order_ledger_visible')}`")
        lines.append('')
        lines.append('## Workflow Screenshots')
        lines.append('')
        for file_name in frontend.get('screenshots', []) or traffic.get('screenshots', []):
            lines.append(f'![{file_name}](screenshots/{file_name})')
            lines.append('')
        return '\n'.join(lines)
